// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wntvimopezffjtcwnobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudHZpbW9wZXpmZmp0Y3dub2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTc5NzQsImV4cCI6MjA3MTI5Mzk3NH0.hyE-SZLv3EyzncrcqqI9hBlG0IRs9ipD1ow0zfmVpBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});